core:
  _callback:    "_clbk"
  _format:      "_fmt"
  _locale:      "_lcl"
  _page_number: "_pgNm"
  _page_size:   "_pgSz"
  _rt:          "_rt"
  _sort:        "_ordSrt"

active:      "active"
competition: "comp"
contestant:  "ctst"
detailed:    "detailed"
fixture:     "fx"
lineups:     "lineups"
live:        "live"
match_date:  "mt.mDt"
match_time:  "mt.mDt"
people:      "people"
person:      "prsn"
stage:       "stg"
status:      "status"
tournament:  "tmcl"
type:        "type"
venue:       "venue"
